### ISSUE TITLE
Jade is depricated

### ISSUE THREAD

**Issue by MrKieren** [rquadling/grunt-html2js#83]
grunt-html2js has a dependency for jade ^1.3.1 which now deprecated:

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

**Comment by andela-idurotola** [comment]
has this been fixed or does it auto detect .pug files too?

**Comment by wcjr** [comment]
@MrKieren ,you might consider a PR for this one just in case @karlgoldstein isn't able to get to this anytime soon.

**Comment by agenaille** [comment]
+1 We have upgraded to Pug and have just found our templates are no longer rendering to JS, as we renamed all the .jade templates to .pug. I guess this'll take a major release to fix. Any support would be much appreciated! Very nice module by the way!

**Comment by Abdisalan** [comment]
Is this issue due been fixed soon? I see an open PR from Jan 17

**Comment by wcjr** [comment]
@rquadling , mind if we get a `0.4.0` tag on this?

**Comment by rquadling** [comment]
Oh! Sorry!!!

**Comment by rquadling** [comment]
https://github.com/rquadling/grunt-html2js/releases/tag/0.4.0
https://www.npmjs.com/package/grunt-html2js

**Comment by wcjr** [comment]
no problem, my workflow for tags almost always involves someone reminding me to tag it ;-)  appreciate the quick turnaround

**Comment by wcjr** [comment]
Looks like this isn't fixed yet so the same deprecation warnings will continue until this is changed:  https://github.com/rquadling/grunt-html2js/blob/master/package.json#L48

@Abdisalan @rquadling FYI

**Comment by rquadling** [comment]
One issue I cannot resolve is if someone is using Jade templates, Pug will not pick up on Jade includes.

So, for the time being, V0.4 will support both pug and jade (with the deprecation notice). V0.5 will deprecate jade support entirely.

**Comment by wcjr** [comment]
fair enough, sorry it's been such a nuisance.  I can definitely live with the warnings.

**Comment by rquadling** [comment]
Not a nuisance. I'm new to JS at this level. I'm a PHP dev, but some of the tools I use have been unsupported for such a long time that taking them over and maintaining them (to the best of my ability) was the only option.

OOI, I've not used Jade or Pug and only rely on the unit tests to say things are OK. How popular are they?

I'll release a 0.5.0 next week so that allows anyone still needing Jade to have a forward compatible version (0.4.0) to migrate their templates with.

**Comment by wcjr** [comment]
That's a tough position to be in, sorry that fell on you man!

I have no idea how popular those are, I'd never heard of them until these deprecations started popping up.

Thanks for the upcoming release, hang in there!

**Comment by agenaille** [comment]
@rquadling In regards to supporting jade and pug in v0.4 and then deprecating jade in v0.5, wouldn't that potentially break dev teams html2js builds whom are still using jade? Essentially anyone using a package.json dependency value similar to this would automatically pull in v0.5 and break their jade templates html2js build:

`"grunt-html2js": "^0.3.5",`

Sticking to semantic versioning, since a release like this could possibly break backwards compatibility, it may be wise to do a 1.0.0 release so that developers taking all patch and minor releases are not affected. What do you think?

**Comment by rquadling** [comment]
In semver, V0 is "special". http://semver.org/#spec-item-4 / https://getcomposer.org/doc/articles/versions.md#caret-version-range-

So ^0.4 will allow for all release < 0.5.0

So, if there is anything that needs fixing and is specifically Jade related, then it can happily sit in the 0.4 branch.
